-- Auto-exported from ICEBERG_TEST_DB.UNITY_CATALOG.V_HIGH_VALUE_CUSTOMERS
CREATE OR REPLACE VIEW ICEBERG_TEST_DB.UNITY_CATALOG.V_HIGH_VALUE_CUSTOMERS AS
SELECT
    customer_id,
    customer_name,
    region,
    lifetime_value
FROM ICEBERG_TEST_DB.UNITY_CATALOG.CUSTOMERS_FROM_DATABRICKS
WHERE lifetime_value > 100000;
