-- Snowflake 고유 프로시져: Iceberg 테이블 Refresh 상태 점검
CREATE OR ALTER PROCEDURE ICEBERG_TEST_DB.META.SP_REFRESH_CHECK()
  RETURNS VARCHAR
  LANGUAGE SQL
  EXECUTE AS CALLER
AS
BEGIN
  LET result VARCHAR := '';
  -- 마지막 refresh 시각 확인
  SELECT MAX(LAST_REFRESH_TS)::VARCHAR INTO :result
  FROM ICEBERG_TEST_DB.META.ICEBERG_SCHEMA_TRACKING;
  RETURN 'Last refresh: ' || :result;
END;
