-- Test: DEFINE statements via Git Integration (EXECUTE IMMEDIATE FROM)
DEFINE TABLE KT_POC_DB.RAW.GIT_DEFINE_TEST (
  ID NUMBER AUTOINCREMENT,
  NAME VARCHAR(200),
  STATUS VARCHAR(20) DEFAULT 'ACTIVE',
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE VIEW KT_POC_DB.RAW.V_GIT_DEFINE_TEST
AS
SELECT ID, NAME, STATUS FROM KT_POC_DB.RAW.GIT_DEFINE_TEST WHERE STATUS = 'ACTIVE';
